language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tumblr' ]; then cd .. && eval "mv $currentfolder generator-tumblr" && cd generator-tumblr; fi

